### ISSUE TITLE
IR transceiver

### ISSUE THREAD

**Issue by PaskoMoto** [blafois/Daikin-IR-Reverse#4]
Hi.
I'm planning to control a Daikin AC device from a computer, preferably with an USB-to-IR adapter, but I don't know which hardware to buy. :)
Did you use the diode in your schema to send frames to your Daikin device or did you use an specific device? If so, Which device did you use?
Best regards.
EDIT: Sorry already saw in a previous issue you used a led. :)

**Comment by blafois** [comment]
Hi,
Yes I used an IR led with an arduino. Arduino is convenient because of built in PWM (the signal is pulse modulated). I suggest you write an arduino sketch that you then control over USB (serial protocol).

**Comment by PaskoMoto** [comment]
Hi,
thank you for your kind answer.
Regards.
